### ISSUE TITLE
Facing problem.

### ISSUE THREAD

**Issue by sunnysheth** [AshMenhennett/Notebook#7]
Hi,

This is sunny sheth in india.
I've follow every single steps of your amazing project in my new fresh project.
But i got blank screen when i test it.
Need your help.

Thanks in advance.
Sunny

**Comment by AshMenhennett** [comment]
Hi Sheth,

Thanks for checking out this repo. 

In response to your question:
Are you using [Homestead](https://laravel.com/docs/5.3/homestead)? 

If so, all you need to do is:
1. Clone repo.
2. Configure your dev environment (if you are using homestead- configure your ```etc/hosts``` and ```.homestead/Homestead.yaml``` files).
3. Run ```composer install``` on the VM.
4. Configure your ```.env``` file.
5. Load up the url in your browser. E.g http://notebook.app:8000.

You should see the welome screen.

**Comment by sunnysheth** [comment]
Hi


It's working fine now.Thanks.

I would say you are so good at vueJs.

I'm looking forward to see your upcoming work on github.


Thanks again.


________________________________
